schema_version = "1.0.0"

# Unique identifier (use lowercase, no spaces)
id = "add_automerge_header"
version = "1.0.0"
name = "Add Automerge To Top Header"
tagline = "Brings the Auto Merge toggle and threshold to the topmost 3D header in Edit Mode."
maintainer = "Illogicoma <https://github.com/Illogicoma>"
type = "add-on"

# Permissions (this addon doesn't need special access)
permissions = []

# Minimum Blender version
blender_version_min = "5.0.0"

# License (SPDX format)
license = [
    "SPDX:GPL-3.0-or-later",
]

# Optional: Tags for the extension manager

tags = ["Interface", "Modeling"]

